[build]
  publish = "public"
  command = "hugo --gc"
  
[build.environment]
  HUGO_VERSION = "0.89.4+extended"
  HUGO_THEME = "redlab-hugo"
  
[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"  
  
  [build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.88.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/npmjs/*"
  to = "/npmjs/"
  status = 200
